services:
  zoneminder:
    build: "./build/"
    container_name: zoneminder
    image: zoneminder:v1.0.0
    restart: unless-stopped
    ports:
      - "9002:9000"
      - "8080:80"
    privileged: false
    shm_size: 4G
    environment:
      TZ: "America/Chicago"
    volumes:
      # Temporary fix to enable API due to debian packaging bug
      - ./zm-api.conf:/etc/apache2/conf-enabled/zm-api.conf:ro
      - type: bind
        source: "/some/path/on/your/computer/images"
        target: "/var/cache/zoneminder/images"
      - type: bind
        source: "/some/path/on/your/computer/events"
        target: "/var/cache/zoneminder/events"
      - type: bind
        source: "/some/path/on/your/computer/zm_db"
        target: "/var/lib/mysql"

